# Generated by Django 5.2.4 on 2025-08-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='(No comment)'),
        ),
    ]
